name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install PostCSS
        run: |
          npm install postcss-cli autoprefixer

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Hugo Site
        run: hugo --minify
        # run: hugo --minify --theme docsy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
          publish_branch: gh-pages
